# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [3]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
x = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
y = np.array([
    [1,2],
    [3,4]
    ])

# Create a 3-dimensional Numpy array using np.array()
z = np.array([
    [[1,2],[3,4]],
    [[5,6],[6,7]]
    ])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [11]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print(x.shape)
print(x.ndim)
print(x.dtype)
print(x.size)
print(type(x))

(3,)
1
int32
3
<class 'numpy.ndarray'>


In [12]:
# Attributes of 2-dimensional array
print(y.shape)
print(y.ndim)
print(y.dtype)
print(y.size)
print(type(y))

(2, 2)
2
int32
4
<class 'numpy.ndarray'>


In [13]:
# Attributes of 3-dimensional array
print(z.shape)
print(z.ndim)
print(z.dtype)
print(z.size)
print(type(z))

(2, 2, 2)
3
int32
8
<class 'numpy.ndarray'>


In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(y)
df

0  1
0  1  2
1  3  4

In [20]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10,2))

In [23]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((7,2,3))

In [25]:
# Create an array within a range of 0 and 100 with step 3
arr_S = np.arange(0,101,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [28]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_N = np.random.randint(0,10,(7,2))

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_f = np.random.random((3,5))

In [40]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_N = np.random.randint(0,10,(4,6))

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [47]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(1,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
# Find the 0'th index of the latest array you created
arr[0][0]

1

In [54]:
# Get the first 2 rows of latest array you created
x = arr[0:2,:]
x

array([[1, 4, 7, 2, 3, 1, 5],
       [1, 8, 1, 1, 2, 2, 6]])

In [56]:
# Get the first 2 values of the first 2 rows of the latest array
print(x[0][0])
print(x[1][0])

1
1


In [58]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
rand_arr = np.random.randint(0,10,(3,5))
ones_arr = np.ones((3,5))

In [61]:
# Add the two arrays together
pro_arr = rand_arr + ones_arr
pro_arr

array([[10.,  6.,  7.,  4.,  7.],
       [ 8.,  1.,  6.,  8.,  5.],
       [ 4.,  2.,  6.,  6.,  1.]])

In [60]:
# Create another array of ones of shape (5, 3)
sec_ones_arr = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together

## this produce an error as the size of two arrayes are differant

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
ones_arr = np.ones((3,5))

In [66]:
# Subtract the new array of ones from the other most recent array
arr = ones_arr * pro_arr
arr

array([[10.,  6.,  7.,  4.,  7.],
       [ 8.,  1.,  6.,  8.,  5.],
       [ 4.,  2.,  6.,  6.,  1.]])

In [67]:
# Multiply the ones array with the latest array
arr = ones_arr / arr
arr

array([[0.1       , 0.16666667, 0.14285714, 0.25      , 0.14285714],
       [0.125     , 1.        , 0.16666667, 0.125     , 0.2       ],
       [0.25      , 0.5       , 0.16666667, 0.16666667, 1.        ]])

In [68]:
# Take the latest array to the power of 2 using '**'
arr**2

array([[0.01      , 0.02777778, 0.02040816, 0.0625    , 0.02040816],
       [0.015625  , 1.        , 0.02777778, 0.015625  , 0.04      ],
       [0.0625    , 0.25      , 0.02777778, 0.02777778, 1.        ]])

In [70]:
# Do the same thing with np.square()
arr =np.square(arr)
arr

array([[0.01      , 0.02777778, 0.02040816, 0.0625    , 0.02040816],
       [0.015625  , 1.        , 0.02777778, 0.015625  , 0.04      ],
       [0.0625    , 0.25      , 0.02777778, 0.02777778, 1.        ]])

In [71]:
# Find the mean of the latest array using np.mean()
np.mean(arr)

0.17387849584278156

In [72]:
# Find the maximum of the latest array using np.max()
np.max(arr)

1.0

In [73]:
# Find the minimum of the latest array using np.min()
np.min(arr)

0.010000000000000002

In [74]:
# Find the standard deviation of the latest array
np.std(arr)

0.3289289910715878

In [75]:
# Find the variance of the latest array
np.var(arr)

0.10819428116737267

In [76]:
# Reshape the latest array to (3, 5, 1)
arr.reshape(3,5,1)

array([[[0.01      ],
        [0.02777778],
        [0.02040816],
        [0.0625    ],
        [0.02040816]],

       [[0.015625  ],
        [1.        ],
        [0.02777778],
        [0.015625  ],
        [0.04      ]],

       [[0.0625    ],
        [0.25      ],
        [0.02777778],
        [0.02777778],
        [1.        ]]])

In [77]:
# Transpose the latest array
np.transpose(arr)

array([[0.01      , 0.015625  , 0.0625    ],
       [0.02777778, 1.        , 0.25      ],
       [0.02040816, 0.02777778, 0.02777778],
       [0.0625    , 0.015625  , 0.02777778],
       [0.02040816, 0.04      , 1.        ]])

What does the transpose do?

In [78]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,2))

In [79]:
# Perform a dot product on the two newest arrays you created
np.dot(arr1,arr2)

array([[ 39, 102],
       [ 18,  56],
       [ 33,  84]])

In [84]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(0,10,(4,3))
arr4 = np.random.randint(0,10,(4,3))

In [81]:
# Perform a dot product on the two newest arrays you created
np.dot(arr3,arr4)
# does not work , so we can transpoes one of them and then make dot product on them

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [85]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3 = np.transpose(arr3)
np.dot(arr3,arr4)

array([[ 96,  37, 107],
       [ 95,  32,  89],
       [ 74,  31,  54]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [106]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array1 = np.random.randint(0,10,(2,2))
array2 = np.random.randint(0,10,(2,2))


In [107]:
# Compare the two arrays with '>'
array2>array1

array([[False,  True],
       [False, False]])

What happens when you compare the arrays with `>`?

In [108]:
# Compare the two arrays with '>='
array2>=array1

array([[ True,  True],
       [False, False]])

In [109]:
# Find which elements of the first array are greater than 7
x = array1[ array1>7]
x

array([8])

In [110]:
# Which parts of each array are equal? (try using '==')
array1 == array2

array([[ True, False],
       [False, False]])

In [111]:
# Sort one of the arrays you just created in ascending order
array2.sort()

In [114]:
# Sort the indexes of one of the arrays you just created
np.argsort(array1)
np.argsort(array2)

array([[0, 1],
       [0, 1]], dtype=int64)

In [116]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array1)
np.argmax(array2)

1

In [117]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
array1.argmax(axis=0)

array([0, 1], dtype=int64)

In [118]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
array2.argmin(axis=1)

array([0, 0], dtype=int64)

In [122]:
# Create an array of normally distributed random numbers
rng = np.random.default_rng()
numbers = rng.normal(size=10_000)
numbers

array([ 0.68208617,  0.13276519, -0.56663588, ..., -1.19730447,
       -0.03526839,  0.34686731])

In [124]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.